import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'satish',
      email: 'admin@example.com',
      password: bcrypt.hashSync('satish'),
      isAdmin: true,
    },
    {
      name: 'reddy',
      email: 'user@example.com',
      password: bcrypt.hashSync('reddy'),
      isAdmin: false,
    },
  ],

  categories: [
    {
      categoryName: 'Men',
      categoryDescription: 'Mens Collection',
    },
    {
      categoryName: 'Women',
      categoryDescription: 'Womens Collection',
    },
    {
      categoryName: 'Kids',
      categoryDescription: 'Kids Collection',
    },
  ],

  products: [
    {
      name: 'White Cot',
      slug: 'white-cot',
      category: 'Cot',
      image: '/images/white-cot.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular Cots',
    },
    {
      name: 'Sofa',
      slug: 'sofa',
      category: 'Sofa',
      image: '/images/sofa.jpg',
      price: 80,
      brand: 'Sofa',
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Sofa',
    },
    {
      name: 'Bed',
      slug: 'bed',
      category: 'Bed',
      image: '/images/bed.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular Bed',
    },
    {
      name: 'Dinning Chairs',
      slug: 'dinning-chairs',
      category: 'Pants',
      image: '/images/dinning-chairs.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking Dinning CHairs',
    },
    {
      name: 'Sofa Flowering',
      slug: 'sofa-flowering',
      category: 'Sofa',
      image: '/images/sofa2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 3.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A popular Sofa Flowering',
    },
    {
      name: 'Chair',
      slug: 'chair',
      category: 'Pants',
      image: '/images/chair.jpg',
      price: 75,
      brand: 'Casely',
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular Chair',
    },
  ],
};
export default data;
